name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutterando_analysis: ^0.0.2
  test: ^1.21.0
dependencies:
  postgresql2: ^1.0.4
  redis: ^3.1.0
  result_dart: ^1.0.5
  shelf: ^1.4.0
  shelf_modular: ^2.1.0
  uno: ^1.1.6
